apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descaler-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descaler-edit
subjects:
- kind: ServiceAccount
  name: descaler
  namespace: descaler
