/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecVsphereVolume : VsphereVolume represents a vSphere volume attached and mounted on kubelets host machine



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecVsphereVolume {
    /// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// Storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName.
    #[serde(rename = "storagePolicyID", skip_serializing_if = "Option::is_none")]
    pub storage_policy_id: Option<String>,
    /// Storage Policy Based Management (SPBM) profile name.
    #[serde(rename = "storagePolicyName", skip_serializing_if = "Option::is_none")]
    pub storage_policy_name: Option<String>,
    /// Path that identifies vSphere volume vmdk
    #[serde(rename = "volumePath")]
    pub volume_path: String,
}

impl ScaledJobJobTargetRefTemplateSpecVsphereVolume {
    /// VsphereVolume represents a vSphere volume attached and mounted on kubelets host machine
    pub fn new(volume_path: String) -> ScaledJobJobTargetRefTemplateSpecVsphereVolume {
        ScaledJobJobTargetRefTemplateSpecVsphereVolume {
            fs_type: None,
            storage_policy_id: None,
            storage_policy_name: None,
            volume_path,
        }
    }
}


