/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRef : JobSpec describes how the job execution will look like.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRef {
    /// Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    #[serde(rename = "activeDeadlineSeconds", skip_serializing_if = "Option::is_none")]
    pub active_deadline_seconds: Option<i64>,
    /// Specifies the number of retries before marking this job failed. Defaults to 6
    #[serde(rename = "backoffLimit", skip_serializing_if = "Option::is_none")]
    pub backoff_limit: Option<i32>,
    /// Specifies the desired number of successfully finished pods the job should be run with.  Setting to nil means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    #[serde(rename = "completions", skip_serializing_if = "Option::is_none")]
    pub completions: Option<i32>,
    /// manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector
    #[serde(rename = "manualSelector", skip_serializing_if = "Option::is_none")]
    pub manual_selector: Option<bool>,
    /// Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    #[serde(rename = "parallelism", skip_serializing_if = "Option::is_none")]
    pub parallelism: Option<i32>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<crate::models::ScaledJobJobTargetRefSelector>,
    #[serde(rename = "template")]
    pub template: crate::models::ScaledJobJobTargetRefTemplate,
    /// ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes. This field is alpha-level and is only honored by servers that enable the TTLAfterFinished feature.
    #[serde(rename = "ttlSecondsAfterFinished", skip_serializing_if = "Option::is_none")]
    pub ttl_seconds_after_finished: Option<i32>,
}

impl ScaledJobJobTargetRef {
    /// JobSpec describes how the job execution will look like.
    pub fn new(template: crate::models::ScaledJobJobTargetRefTemplate) -> ScaledJobJobTargetRef {
        ScaledJobJobTargetRef {
            active_deadline_seconds: None,
            backoff_limit: None,
            completions: None,
            manual_selector: None,
            parallelism: None,
            selector: None,
            template,
            ttl_seconds_after_finished: None,
        }
    }
}


