/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecSecurityContext2Sysctls : Sysctl defines a kernel parameter to be set



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecSecurityContext2Sysctls {
    /// Name of a property to set
    #[serde(rename = "name")]
    pub name: String,
    /// Value of a property to set
    #[serde(rename = "value")]
    pub value: String,
}

impl ScaledJobJobTargetRefTemplateSpecSecurityContext2Sysctls {
    /// Sysctl defines a kernel parameter to be set
    pub fn new(name: String, value: String) -> ScaledJobJobTargetRefTemplateSpecSecurityContext2Sysctls {
        ScaledJobJobTargetRefTemplateSpecSecurityContext2Sysctls {
            name,
            value,
        }
    }
}


