/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTerm : Required. A pod affinity term, associated with the corresponding weight.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTerm {
    #[serde(rename = "labelSelector", skip_serializing_if = "Option::is_none")]
    pub label_selector: Option<crate::models::ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTermLabelSelector>,
    /// namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means \"this pod's namespace\"
    #[serde(rename = "namespaces", skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<Vec<String>>,
    /// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
    #[serde(rename = "topologyKey")]
    pub topology_key: String,
}

impl ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTerm {
    /// Required. A pod affinity term, associated with the corresponding weight.
    pub fn new(topology_key: String) -> ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTerm {
        ScaledJobJobTargetRefTemplateSpecAffinityPodAffinityPodAffinityTerm {
            label_selector: None,
            namespaces: None,
            topology_key,
        }
    }
}


