/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecSecurityContextCapabilities : The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecSecurityContextCapabilities {
    /// Added capabilities
    #[serde(rename = "add", skip_serializing_if = "Option::is_none")]
    pub add: Option<Vec<String>>,
    /// Removed capabilities
    #[serde(rename = "drop", skip_serializing_if = "Option::is_none")]
    pub drop: Option<Vec<String>>,
}

impl ScaledJobJobTargetRefTemplateSpecSecurityContextCapabilities {
    /// The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecSecurityContextCapabilities {
        ScaledJobJobTargetRefTemplateSpecSecurityContextCapabilities {
            add: None,
            drop: None,
        }
    }
}


