/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecConfigMapItems : Maps a string key to a path within a volume.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecConfigMapItems {
    /// The key to project.
    #[serde(rename = "key")]
    pub key: String,
    /// Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<i32>,
    /// The relative path of the file to map the key to. May not be an absolute path. May not contain the path element '..'. May not start with the string '..'.
    #[serde(rename = "path")]
    pub path: String,
}

impl ScaledJobJobTargetRefTemplateSpecConfigMapItems {
    /// Maps a string key to a path within a volume.
    pub fn new(key: String, path: String) -> ScaledJobJobTargetRefTemplateSpecConfigMapItems {
        ScaledJobJobTargetRefTemplateSpecConfigMapItems {
            key,
            mode: None,
            path,
        }
    }
}


