/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecValueFrom : Source for the environment variable's value. Cannot be used if value is not empty.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecValueFrom {
    #[serde(rename = "configMapKeyRef", skip_serializing_if = "Option::is_none")]
    pub config_map_key_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecValueFromConfigMapKeyRef>,
    #[serde(rename = "fieldRef", skip_serializing_if = "Option::is_none")]
    pub field_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecValueFromFieldRef>,
    #[serde(rename = "resourceFieldRef", skip_serializing_if = "Option::is_none")]
    pub resource_field_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef>,
    #[serde(rename = "secretKeyRef", skip_serializing_if = "Option::is_none")]
    pub secret_key_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef>,
}

impl ScaledJobJobTargetRefTemplateSpecValueFrom {
    /// Source for the environment variable's value. Cannot be used if value is not empty.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecValueFrom {
        ScaledJobJobTargetRefTemplateSpecValueFrom {
            config_map_key_ref: None,
            field_ref: None,
            resource_field_ref: None,
            secret_key_ref: None,
        }
    }
}


