/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders : HTTPHeader describes a custom header to be used in HTTP probes



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders {
    /// The header field name
    #[serde(rename = "name")]
    pub name: String,
    /// The header field value
    #[serde(rename = "value")]
    pub value: String,
}

impl ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders {
    /// HTTPHeader describes a custom header to be used in HTTP probes
    pub fn new(name: String, value: String) -> ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders {
        ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders {
            name,
            value,
        }
    }
}


