/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecCsi : CSI (Container Storage Interface) represents storage that is handled by an external CSI driver (Alpha feature).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecCsi {
    /// Driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
    #[serde(rename = "driver")]
    pub driver: String,
    /// Filesystem type to mount. Ex. \"ext4\", \"xfs\", \"ntfs\". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    #[serde(rename = "nodePublishSecretRef", skip_serializing_if = "Option::is_none")]
    pub node_publish_secret_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecCsiNodePublishSecretRef>,
    /// Specifies a read-only configuration for the volume. Defaults to false (read/write).
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// VolumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver's documentation for supported values.
    #[serde(rename = "volumeAttributes", skip_serializing_if = "Option::is_none")]
    pub volume_attributes: Option<::std::collections::HashMap<String, String>>,
}

impl ScaledJobJobTargetRefTemplateSpecCsi {
    /// CSI (Container Storage Interface) represents storage that is handled by an external CSI driver (Alpha feature).
    pub fn new(driver: String) -> ScaledJobJobTargetRefTemplateSpecCsi {
        ScaledJobJobTargetRefTemplateSpecCsi {
            driver,
            fs_type: None,
            node_publish_secret_ref: None,
            read_only: None,
            volume_attributes: None,
        }
    }
}


