/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecDownwardApiFieldRef : Required: Selects a field of the pod: only annotations, labels, name and namespace are supported.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecDownwardApiFieldRef {
    /// Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// Path of the field to select in the specified API version.
    #[serde(rename = "fieldPath")]
    pub field_path: String,
}

impl ScaledJobJobTargetRefTemplateSpecDownwardApiFieldRef {
    /// Required: Selects a field of the pod: only annotations, labels, name and namespace are supported.
    pub fn new(field_path: String) -> ScaledJobJobTargetRefTemplateSpecDownwardApiFieldRef {
        ScaledJobJobTargetRefTemplateSpecDownwardApiFieldRef {
            api_version: None,
            field_path,
        }
    }
}


