/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGet : HTTPGet specifies the http request to perform.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGet {
    /// Host name to connect to, defaults to the pod IP. You probably want to set \"Host\" in httpHeaders instead.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Custom headers to set in the request. HTTP allows repeated headers.
    #[serde(rename = "httpHeaders", skip_serializing_if = "Option::is_none")]
    pub http_headers: Option<Vec<crate::models::ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGetHttpHeaders>>,
    /// Path to access on the HTTP server.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
    #[serde(rename = "port")]
    pub port: String,
    /// Scheme to use for connecting to the host. Defaults to HTTP.
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<String>,
}

impl ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGet {
    /// HTTPGet specifies the http request to perform.
    pub fn new(port: String) -> ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGet {
        ScaledJobJobTargetRefTemplateSpecLifecyclePostStartHttpGet {
            host: None,
            http_headers: None,
            path: None,
            port,
            scheme: None,
        }
    }
}


