/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecFlexVolume : FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecFlexVolume {
    /// Driver is the name of the driver to use for this volume.
    #[serde(rename = "driver")]
    pub driver: String,
    /// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default filesystem depends on FlexVolume script.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// Optional: Extra command options if any.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<::std::collections::HashMap<String, String>>,
    /// Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "secretRef", skip_serializing_if = "Option::is_none")]
    pub secret_ref: Option<crate::models::ScaledJobJobTargetRefTemplateSpecFlexVolumeSecretRef>,
}

impl ScaledJobJobTargetRefTemplateSpecFlexVolume {
    /// FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.
    pub fn new(driver: String) -> ScaledJobJobTargetRefTemplateSpecFlexVolume {
        ScaledJobJobTargetRefTemplateSpecFlexVolume {
            driver,
            fs_type: None,
            options: None,
            read_only: None,
            secret_ref: None,
        }
    }
}


