/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecReadinessGates : PodReadinessGate contains the reference to a pod condition



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecReadinessGates {
    /// ConditionType refers to a condition in the pod's condition list with matching type.
    #[serde(rename = "conditionType")]
    pub condition_type: String,
}

impl ScaledJobJobTargetRefTemplateSpecReadinessGates {
    /// PodReadinessGate contains the reference to a pod condition
    pub fn new(condition_type: String) -> ScaledJobJobTargetRefTemplateSpecReadinessGates {
        ScaledJobJobTargetRefTemplateSpecReadinessGates {
            condition_type,
        }
    }
}


