/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecQuobyte : Quobyte represents a Quobyte mount on the host that shares a pod's lifetime



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecQuobyte {
    /// Group to map volume access to Default is no group
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// ReadOnly here will force the Quobyte volume to be mounted with read-only permissions. Defaults to false.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// Registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes
    #[serde(rename = "registry")]
    pub registry: String,
    /// Tenant owning the given Quobyte volume in the Backend Used with dynamically provisioned Quobyte volumes, value is set by the plugin
    #[serde(rename = "tenant", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<String>,
    /// User to map volume access to Defaults to serivceaccount user
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// Volume is a string that references an already created Quobyte volume by name.
    #[serde(rename = "volume")]
    pub volume: String,
}

impl ScaledJobJobTargetRefTemplateSpecQuobyte {
    /// Quobyte represents a Quobyte mount on the host that shares a pod's lifetime
    pub fn new(registry: String, volume: String) -> ScaledJobJobTargetRefTemplateSpecQuobyte {
        ScaledJobJobTargetRefTemplateSpecQuobyte {
            group: None,
            read_only: None,
            registry,
            tenant: None,
            user: None,
            volume,
        }
    }
}


