/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef : Selects a key of a secret in the pod's namespace



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef {
    /// The key of the secret to select from.  Must be a valid secret key.
    #[serde(rename = "key")]
    pub key: String,
    /// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef {
    /// Selects a key of a secret in the pod's namespace
    pub fn new(key: String) -> ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef {
        ScaledJobJobTargetRefTemplateSpecValueFromSecretKeyRef {
            key,
            name: None,
            optional: None,
        }
    }
}


