/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi : information about the downwardAPI data to project



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi {
    /// Items is a list of DownwardAPIVolume file
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ScaledJobJobTargetRefTemplateSpecDownwardApiItems>>,
}

impl ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi {
    /// information about the downwardAPI data to project
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi {
        ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi {
            items: None,
        }
    }
}


