/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecScaleIo : ScaleIO represents a ScaleIO persistent volume attached and mounted on Kubernetes nodes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecScaleIo {
    /// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\".
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// The host address of the ScaleIO API Gateway.
    #[serde(rename = "gateway")]
    pub gateway: String,
    /// The name of the ScaleIO Protection Domain for the configured storage.
    #[serde(rename = "protectionDomain", skip_serializing_if = "Option::is_none")]
    pub protection_domain: Option<String>,
    /// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "secretRef")]
    pub secret_ref: crate::models::ScaledJobJobTargetRefTemplateSpecScaleIoSecretRef,
    /// Flag to enable/disable SSL communication with Gateway, default false
    #[serde(rename = "sslEnabled", skip_serializing_if = "Option::is_none")]
    pub ssl_enabled: Option<bool>,
    /// Indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned.
    #[serde(rename = "storageMode", skip_serializing_if = "Option::is_none")]
    pub storage_mode: Option<String>,
    /// The ScaleIO Storage Pool associated with the protection domain.
    #[serde(rename = "storagePool", skip_serializing_if = "Option::is_none")]
    pub storage_pool: Option<String>,
    /// The name of the storage system as configured in ScaleIO.
    #[serde(rename = "system")]
    pub system: String,
    /// The name of a volume already created in the ScaleIO system that is associated with this volume source.
    #[serde(rename = "volumeName", skip_serializing_if = "Option::is_none")]
    pub volume_name: Option<String>,
}

impl ScaledJobJobTargetRefTemplateSpecScaleIo {
    /// ScaleIO represents a ScaleIO persistent volume attached and mounted on Kubernetes nodes.
    pub fn new(gateway: String, secret_ref: crate::models::ScaledJobJobTargetRefTemplateSpecScaleIoSecretRef, system: String) -> ScaledJobJobTargetRefTemplateSpecScaleIo {
        ScaledJobJobTargetRefTemplateSpecScaleIo {
            fs_type: None,
            gateway,
            protection_domain: None,
            read_only: None,
            secret_ref,
            ssl_enabled: None,
            storage_mode: None,
            storage_pool: None,
            system,
            volume_name: None,
        }
    }
}


