/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecPhotonPersistentDisk : PhotonPersistentDisk represents a PhotonController persistent disk attached and mounted on kubelets host machine



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecPhotonPersistentDisk {
    /// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// ID that identifies Photon Controller persistent disk
    #[serde(rename = "pdID")]
    pub pd_id: String,
}

impl ScaledJobJobTargetRefTemplateSpecPhotonPersistentDisk {
    /// PhotonPersistentDisk represents a PhotonController persistent disk attached and mounted on kubelets host machine
    pub fn new(pd_id: String) -> ScaledJobJobTargetRefTemplateSpecPhotonPersistentDisk {
        ScaledJobJobTargetRefTemplateSpecPhotonPersistentDisk {
            fs_type: None,
            pd_id,
        }
    }
}


