/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecDnsConfigOptions : PodDNSConfigOption defines DNS resolver options of a pod.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecDnsConfigOptions {
    /// Required.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ScaledJobJobTargetRefTemplateSpecDnsConfigOptions {
    /// PodDNSConfigOption defines DNS resolver options of a pod.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecDnsConfigOptions {
        ScaledJobJobTargetRefTemplateSpecDnsConfigOptions {
            name: None,
            value: None,
        }
    }
}


