/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreference : A node selector term, associated with the corresponding weight.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreference {
    /// A list of node selector requirements by node's labels.
    #[serde(rename = "matchExpressions", skip_serializing_if = "Option::is_none")]
    pub match_expressions: Option<Vec<crate::models::ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreferenceMatchExpressions>>,
    /// A list of node selector requirements by node's fields.
    #[serde(rename = "matchFields", skip_serializing_if = "Option::is_none")]
    pub match_fields: Option<Vec<crate::models::ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreferenceMatchExpressions>>,
}

impl ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreference {
    /// A node selector term, associated with the corresponding weight.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreference {
        ScaledJobJobTargetRefTemplateSpecAffinityNodeAffinityPreference {
            match_expressions: None,
            match_fields: None,
        }
    }
}


