/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecDownwardApi : DownwardAPI represents downward API about the pod that should populate this volume



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecDownwardApi {
    /// Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    #[serde(rename = "defaultMode", skip_serializing_if = "Option::is_none")]
    pub default_mode: Option<i32>,
    /// Items is a list of downward API volume file
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ScaledJobJobTargetRefTemplateSpecDownwardApiItems>>,
}

impl ScaledJobJobTargetRefTemplateSpecDownwardApi {
    /// DownwardAPI represents downward API about the pod that should populate this volume
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecDownwardApi {
        ScaledJobJobTargetRefTemplateSpecDownwardApi {
            default_mode: None,
            items: None,
        }
    }
}


