/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecLifecycle : Actions that the management system should take in response to container lifecycle events. Cannot be updated.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecLifecycle {
    #[serde(rename = "postStart", skip_serializing_if = "Option::is_none")]
    pub post_start: Option<crate::models::ScaledJobJobTargetRefTemplateSpecLifecyclePostStart>,
    #[serde(rename = "preStop", skip_serializing_if = "Option::is_none")]
    pub pre_stop: Option<crate::models::ScaledJobJobTargetRefTemplateSpecLifecyclePreStop>,
}

impl ScaledJobJobTargetRefTemplateSpecLifecycle {
    /// Actions that the management system should take in response to container lifecycle events. Cannot be updated.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecLifecycle {
        ScaledJobJobTargetRefTemplateSpecLifecycle {
            post_start: None,
            pre_stop: None,
        }
    }
}


