/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef : Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef {
    /// Container name: required for volumes, optional for env vars
    #[serde(rename = "containerName", skip_serializing_if = "Option::is_none")]
    pub container_name: Option<String>,
    /// Specifies the output format of the exposed resources, defaults to \"1\"
    #[serde(rename = "divisor", skip_serializing_if = "Option::is_none")]
    pub divisor: Option<String>,
    /// Required: resource to select
    #[serde(rename = "resource")]
    pub resource: String,
}

impl ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef {
    /// Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
    pub fn new(resource: String) -> ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef {
        ScaledJobJobTargetRefTemplateSpecValueFromResourceFieldRef {
            container_name: None,
            divisor: None,
            resource,
        }
    }
}


