/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecHostAliases : HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod's hosts file.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecHostAliases {
    /// Hostnames for the above IP address.
    #[serde(rename = "hostnames", skip_serializing_if = "Option::is_none")]
    pub hostnames: Option<Vec<String>>,
    /// IP address of the host file entry.
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
}

impl ScaledJobJobTargetRefTemplateSpecHostAliases {
    /// HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod's hosts file.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecHostAliases {
        ScaledJobJobTargetRefTemplateSpecHostAliases {
            hostnames: None,
            ip: None,
        }
    }
}


