/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecLifecycle1 : Lifecycle is not allowed for ephemeral containers.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecLifecycle1 {
    #[serde(rename = "postStart", skip_serializing_if = "Option::is_none")]
    pub post_start: Option<crate::models::ScaledJobJobTargetRefTemplateSpecLifecyclePostStart>,
    #[serde(rename = "preStop", skip_serializing_if = "Option::is_none")]
    pub pre_stop: Option<crate::models::ScaledJobJobTargetRefTemplateSpecLifecyclePreStop>,
}

impl ScaledJobJobTargetRefTemplateSpecLifecycle1 {
    /// Lifecycle is not allowed for ephemeral containers.
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecLifecycle1 {
        ScaledJobJobTargetRefTemplateSpecLifecycle1 {
            post_start: None,
            pre_stop: None,
        }
    }
}


