/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecPortworxVolume : PortworxVolume represents a portworx volume attached and mounted on kubelets host machine



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecPortworxVolume {
    /// FSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\". Implicitly inferred to be \"ext4\" if unspecified.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// VolumeID uniquely identifies a Portworx volume
    #[serde(rename = "volumeID")]
    pub volume_id: String,
}

impl ScaledJobJobTargetRefTemplateSpecPortworxVolume {
    /// PortworxVolume represents a portworx volume attached and mounted on kubelets host machine
    pub fn new(volume_id: String) -> ScaledJobJobTargetRefTemplateSpecPortworxVolume {
        ScaledJobJobTargetRefTemplateSpecPortworxVolume {
            fs_type: None,
            read_only: None,
            volume_id,
        }
    }
}


