/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecAzureFile : AzureFile represents an Azure File Service mount on the host and bind mount to the pod.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecAzureFile {
    /// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// the name of secret that contains Azure Storage Account Name and Key
    #[serde(rename = "secretName")]
    pub secret_name: String,
    /// Share Name
    #[serde(rename = "shareName")]
    pub share_name: String,
}

impl ScaledJobJobTargetRefTemplateSpecAzureFile {
    /// AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
    pub fn new(secret_name: String, share_name: String) -> ScaledJobJobTargetRefTemplateSpecAzureFile {
        ScaledJobJobTargetRefTemplateSpecAzureFile {
            read_only: None,
            secret_name,
            share_name,
        }
    }
}


