/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecProjectedSources : Projection that may be projected along with other supported volume types



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecProjectedSources {
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<crate::models::ScaledJobJobTargetRefTemplateSpecProjectedConfigMap>,
    #[serde(rename = "downwardAPI", skip_serializing_if = "Option::is_none")]
    pub downward_api: Option<crate::models::ScaledJobJobTargetRefTemplateSpecProjectedDownwardApi>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<crate::models::ScaledJobJobTargetRefTemplateSpecProjectedSecret>,
    #[serde(rename = "serviceAccountToken", skip_serializing_if = "Option::is_none")]
    pub service_account_token: Option<crate::models::ScaledJobJobTargetRefTemplateSpecProjectedServiceAccountToken>,
}

impl ScaledJobJobTargetRefTemplateSpecProjectedSources {
    /// Projection that may be projected along with other supported volume types
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecProjectedSources {
        ScaledJobJobTargetRefTemplateSpecProjectedSources {
            config_map: None,
            downward_api: None,
            secret: None,
            service_account_token: None,
        }
    }
}


