/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobJobTargetRefTemplateSpecFlocker : Flocker represents a Flocker volume attached to a kubelet's host machine. This depends on the Flocker control service being running



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobJobTargetRefTemplateSpecFlocker {
    /// Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated
    #[serde(rename = "datasetName", skip_serializing_if = "Option::is_none")]
    pub dataset_name: Option<String>,
    /// UUID of the dataset. This is unique identifier of a Flocker dataset
    #[serde(rename = "datasetUUID", skip_serializing_if = "Option::is_none")]
    pub dataset_uuid: Option<String>,
}

impl ScaledJobJobTargetRefTemplateSpecFlocker {
    /// Flocker represents a Flocker volume attached to a kubelet's host machine. This depends on the Flocker control service being running
    pub fn new() -> ScaledJobJobTargetRefTemplateSpecFlocker {
        ScaledJobJobTargetRefTemplateSpecFlocker {
            dataset_name: None,
            dataset_uuid: None,
        }
    }
}


