/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledJobAuthenticationRef : ScaledObjectAuthRef points to the TriggerAuthentication object that is used to authenticate the scaler with the environment



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default, JsonSchema)]
pub struct ScaledJobAuthenticationRef {
    #[serde(rename = "name")]
    pub name: String,
}

impl ScaledJobAuthenticationRef {
    /// ScaledObjectAuthRef points to the TriggerAuthentication object that is used to authenticate the scaler with the environment
    pub fn new(name: String) -> ScaledJobAuthenticationRef {
        ScaledJobAuthenticationRef {
            name,
        }
    }
}


