/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StatusConditions : Condition to store the condition state



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusConditions {
    /// A human readable message indicating details about the transition.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The reason for the condition's last transition.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Status of the condition, one of True, False, Unknown.
    #[serde(rename = "status")]
    pub status: String,
    /// Type of condition
    #[serde(rename = "type")]
    pub _type: String,
}

impl StatusConditions {
    /// Condition to store the condition state
    pub fn new(status: String, _type: String) -> StatusConditions {
        StatusConditions {
            message: None,
            reason: None,
            status,
            _type,
        }
    }
}


