/*
 * scaledjobs.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Status : ScaledJobStatus defines the observed state of ScaledJob



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub struct Status {
    /// Conditions an array representation to store multiple Conditions
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::StatusConditions>>,
    #[serde(rename = "lastActiveTime", skip_serializing_if = "Option::is_none")]
    pub last_active_time: Option<String>,
}

impl Status {
    /// ScaledJobStatus defines the observed state of ScaledJob
    pub fn new() -> Status {
        Status {
            conditions: None,
            last_active_time: None,
        }
    }
}


