/*
 * scaledobjects.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehavior : HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehavior {
    #[serde(rename = "scaleDown", skip_serializing_if = "Option::is_none")]
    pub scale_down: Option<crate::models::ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehaviorScaleDown>,
    #[serde(rename = "scaleUp", skip_serializing_if = "Option::is_none")]
    pub scale_up: Option<crate::models::ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUp>,
}

impl ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehavior {
    /// HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).
    pub fn new() -> ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehavior {
        ScaledObjectAdvancedHorizontalPodAutoscalerConfigBehavior {
            scale_down: None,
            scale_up: None,
        }
    }
}


