/*
 * scaledobjects.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledObjectAdvanced : AdvancedConfig specifies advance scaling options



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize,Default, JsonSchema)]
pub struct ScaledObjectAdvanced {
    #[serde(rename = "horizontalPodAutoscalerConfig", skip_serializing_if = "Option::is_none")]
    pub horizontal_pod_autoscaler_config: Option<crate::models::ScaledObjectAdvancedHorizontalPodAutoscalerConfig>,
    #[serde(rename = "restoreToOriginalReplicaCount", skip_serializing_if = "Option::is_none")]
    pub restore_to_original_replica_count: Option<bool>,
}

impl ScaledObjectAdvanced {
    /// AdvancedConfig specifies advance scaling options
    pub fn new() -> ScaledObjectAdvanced {
        ScaledObjectAdvanced {
            horizontal_pod_autoscaler_config: None,
            restore_to_original_replica_count: None,
        }
    }
}


