/*
 * scaledobjects.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledObject : ScaledObjectSpec is the spec for a ScaledObject resource
use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(CustomResource, Default, Clone, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
#[kube(
group = "keda.sh",
kind = "ScaledObject",
version = "v1alpha1",
namespaced,
derive = "PartialEq",
derive = "Default",
apiextensions="v1beta1"
)]
pub struct ScaledObjectSpec {
    #[serde(rename = "advanced", skip_serializing_if = "Option::is_none")]
    pub advanced: Option<crate::models::ScaledObjectAdvanced>,
    #[serde(rename = "cooldownPeriod", skip_serializing_if = "Option::is_none")]
    pub cooldown_period: Option<i32>,
    #[serde(rename = "maxReplicaCount", skip_serializing_if = "Option::is_none")]
    pub max_replica_count: Option<i32>,
    #[serde(rename = "minReplicaCount", skip_serializing_if = "Option::is_none")]
    pub min_replica_count: Option<i32>,
    #[serde(rename = "pollingInterval", skip_serializing_if = "Option::is_none")]
    pub polling_interval: Option<i32>,
    #[serde(rename = "scaleTargetRef")]
    pub scale_target_ref: crate::models::ScaledObjectScaleTargetRef,
    #[serde(rename = "triggers")]
    pub triggers: Vec<crate::models::ScaledObjectTriggers>,
}

impl ScaledObjectSpec {
    // pub fn default() -> Self {
    //     ScaledObjectSpec {
    //         advanced: None,
    //         cooldown_period: None,
    //         max_replica_count: None,
    //         min_replica_count: None,
    //         polling_interval: None,
    //         scale_target_ref: ScaledObjectScaleTargetRef {
    //             api_version: None,
    //             env_source_container_name: None,
    //             kind: None,
    //             name: String::from(""),
    //         },
    //         triggers: vec![],
    //     }
    // }


    /// ScaledObjectSpec is the spec for a ScaledObject resource
    pub fn new(scale_target_ref: crate::models::ScaledObjectScaleTargetRef, triggers: Vec<crate::models::ScaledObjectTriggers>) -> ScaledObjectSpec {
        ScaledObjectSpec {
            advanced: None,
            cooldown_period: None,
            max_replica_count: None,
            min_replica_count: None,
            polling_interval: None,
            scale_target_ref,
            triggers,
        }
    }
}
