/*
 * scaledobjects.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScaledObjectAuthenticationRef : ScaledObjectAuthRef points to the TriggerAuthentication object that is used to authenticate the scaler with the environment



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct ScaledObjectAuthenticationRef {
    #[serde(rename = "name")]
    pub name: String,
}

impl ScaledObjectAuthenticationRef {
    /// ScaledObjectAuthRef points to the TriggerAuthentication object that is used to authenticate the scaler with the environment
    pub fn new(name: String) -> ScaledObjectAuthenticationRef {
        ScaledObjectAuthenticationRef {
            name,
        }
    }
}


