/*
 * scaledobjects.keda.sh
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StatusScaleTargetGvkr : GroupVersionKindResource provides unified structure for schema.GroupVersionKind and Resource



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusScaleTargetGvkr {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl StatusScaleTargetGvkr {
    /// GroupVersionKindResource provides unified structure for schema.GroupVersionKind and Resource
    pub fn new(group: String, kind: String, resource: String, version: String) -> StatusScaleTargetGvkr {
        StatusScaleTargetGvkr {
            group,
            kind,
            resource,
            version,
        }
    }
}


